/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedYearsRouteImport } from './routes/_authenticated/years'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRankingsRouteImport } from './routes/_authenticated/rankings'
import { Route as AuthenticatedModulesRouteImport } from './routes/_authenticated/modules'
import { Route as AuthenticatedGradesRouteImport } from './routes/_authenticated/grades'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedYearReportYearIdRouteImport } from './routes/_authenticated/year-report.$yearId'
import { Route as AuthenticatedBulletinStudentIdRouteImport } from './routes/_authenticated/bulletin.$studentId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYearsRoute = AuthenticatedYearsRouteImport.update({
  id: '/years',
  path: '/years',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingsRoute = AuthenticatedRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModulesRoute = AuthenticatedModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGradesRoute = AuthenticatedGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedYearReportYearIdRoute =
  AuthenticatedYearReportYearIdRouteImport.update({
    id: '/year-report/$yearId',
    path: '/year-report/$yearId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBulletinStudentIdRoute =
  AuthenticatedBulletinStudentIdRouteImport.update({
    id: '/bulletin/$studentId',
    path: '/bulletin/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grades': typeof AuthenticatedGradesRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/years': typeof AuthenticatedYearsRoute
  '/bulletin/$studentId': typeof AuthenticatedBulletinStudentIdRoute
  '/year-report/$yearId': typeof AuthenticatedYearReportYearIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grades': typeof AuthenticatedGradesRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/years': typeof AuthenticatedYearsRoute
  '/bulletin/$studentId': typeof AuthenticatedBulletinStudentIdRoute
  '/year-report/$yearId': typeof AuthenticatedYearReportYearIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/grades': typeof AuthenticatedGradesRoute
  '/_authenticated/modules': typeof AuthenticatedModulesRoute
  '/_authenticated/rankings': typeof AuthenticatedRankingsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/years': typeof AuthenticatedYearsRoute
  '/_authenticated/bulletin/$studentId': typeof AuthenticatedBulletinStudentIdRoute
  '/_authenticated/year-report/$yearId': typeof AuthenticatedYearReportYearIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/classes'
    | '/dashboard'
    | '/grades'
    | '/modules'
    | '/rankings'
    | '/settings'
    | '/students'
    | '/users'
    | '/years'
    | '/bulletin/$studentId'
    | '/year-report/$yearId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/classes'
    | '/dashboard'
    | '/grades'
    | '/modules'
    | '/rankings'
    | '/settings'
    | '/students'
    | '/users'
    | '/years'
    | '/bulletin/$studentId'
    | '/year-report/$yearId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/classes'
    | '/_authenticated/dashboard'
    | '/_authenticated/grades'
    | '/_authenticated/modules'
    | '/_authenticated/rankings'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/users'
    | '/_authenticated/years'
    | '/_authenticated/bulletin/$studentId'
    | '/_authenticated/year-report/$yearId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/years': {
      id: '/_authenticated/years'
      path: '/years'
      fullPath: '/years'
      preLoaderRoute: typeof AuthenticatedYearsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rankings': {
      id: '/_authenticated/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AuthenticatedRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules': {
      id: '/_authenticated/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AuthenticatedModulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grades': {
      id: '/_authenticated/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AuthenticatedGradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/year-report/$yearId': {
      id: '/_authenticated/year-report/$yearId'
      path: '/year-report/$yearId'
      fullPath: '/year-report/$yearId'
      preLoaderRoute: typeof AuthenticatedYearReportYearIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bulletin/$studentId': {
      id: '/_authenticated/bulletin/$studentId'
      path: '/bulletin/$studentId'
      fullPath: '/bulletin/$studentId'
      preLoaderRoute: typeof AuthenticatedBulletinStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGradesRoute: typeof AuthenticatedGradesRoute
  AuthenticatedModulesRoute: typeof AuthenticatedModulesRoute
  AuthenticatedRankingsRoute: typeof AuthenticatedRankingsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedYearsRoute: typeof AuthenticatedYearsRoute
  AuthenticatedBulletinStudentIdRoute: typeof AuthenticatedBulletinStudentIdRoute
  AuthenticatedYearReportYearIdRoute: typeof AuthenticatedYearReportYearIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGradesRoute: AuthenticatedGradesRoute,
  AuthenticatedModulesRoute: AuthenticatedModulesRoute,
  AuthenticatedRankingsRoute: AuthenticatedRankingsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedYearsRoute: AuthenticatedYearsRoute,
  AuthenticatedBulletinStudentIdRoute: AuthenticatedBulletinStudentIdRoute,
  AuthenticatedYearReportYearIdRoute: AuthenticatedYearReportYearIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
